name: CI - Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları checkout et
      uses: actions/checkout@v3

    - name: Node.js kurulumu
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Bağımlılıkları yükle
      run: npm install

    - name: Lint kontrolü
      run: npm run lint

    - name: Unit testleri çalıştır
      run: npm test

